/*=========================================================================

  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
#ifndef __fncAutoGeneratedModule_h
#define __fncAutoGeneratedModule_h

#include "fncModule.h"

class fncAutoGeneratedModule : public fncModule
{
public:
  fncAutoGeneratedModule();
  virtual ~fncAutoGeneratedModule();
  fncTypeMacro(fncAutoGeneratedModule, fncModule);

  /// Parse a string to populate the module.
  bool Initialize(const std::string& definition);

  /// Returns the name for this module.
  virtual const std::string& GetModuleName();

  /// Returns the functor code.
  virtual const std::string& GetFunctorCode();

protected:
  std::string ModuleName;
  std::string FunctorCode;

private:
  fncDisableCopyMacro(fncAutoGeneratedModule);
};

fncDefinePtrMacro(fncAutoGeneratedModule);

#endif
