/*=========================================================================

  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
#include "fncAutoGeneratedModule.h"

//#include <boost/config/warning_disable.hpp>
#include <boost/spirit/include/qi.hpp>
#include <boost/bind.hpp>

/*
===============================================================================
// FUNCTOR MODULE VERSION 0.0.3
// MODULE ${name of the module}
// INPUT ${name}; ${type}; ${default}; ${description}
// INPUT ${name}; ${type}; ${default}; ${description}
// ...
// OUTPUT ${name}; ${type}; ${description}
// OUTPUT ${name}; ${type}; ${description}
// ...

void ${name}_functor(...)
{
}
*/


===============================================================================

//-----------------------------------------------------------------------------
fncAutoGeneratedModule::fncAutoGeneratedModule()
{
}

//-----------------------------------------------------------------------------
fncAutoGeneratedModule::~fncAutoGeneratedModule()
{
}

//-----------------------------------------------------------------------------
const std::string& fncAutoGeneratedModule::GetModuleName()
{
  return this->ModuleName;
}

//-----------------------------------------------------------------------------
const std::string& fncAutoGeneratedModule::GetFunctorCode()
{
  return this->FunctorCode;
}

//-----------------------------------------------------------------------------
bool fncAutoGeneratedModule::Initialize(const std::string& definition)
{

  return false;
}
