/*=========================================================================

  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#include "fncExecutive.h"
#include "fncModule.h"
#include "fncAutoGeneratedModule.h"
#include "PassThrough.cl.h"

int main(int, char**)
{
  fncExecutivePtr executive(new fncExecutive());
  fncAutoGeneratedModulePtr module(new fncAutoGeneratedModule());
  cout << module->Initialize(fncHeaderString_PassThrough) << endl;
  return 0;
}
