/*=========================================================================

  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#include "fncExecutive.h"
#include "fncModule.h"
#include "fncAutoGeneratedModule.h"
#include "fncImageData.h"
#include "PassThrough.cl.h"


#include "assert.h"
#include <string.h>

int main(int, char**)
{
  fncExecutivePtr executive(new fncExecutive());
  fncAutoGeneratedModulePtr moduleA(new fncAutoGeneratedModule());
  assert(moduleA->Initialize(fncHeaderString_PassThrough) != false);

  fncAutoGeneratedModulePtr moduleB(new fncAutoGeneratedModule());
  assert(moduleB->Initialize(fncHeaderString_PassThrough) != false);

  fncAutoGeneratedModulePtr moduleC(new fncAutoGeneratedModule());
  assert(moduleC->Initialize(fncHeaderString_PassThrough) != false);

  executive->Connect(moduleB, "outarray", moduleC, "inarray");
  executive->Connect(moduleA, "outarray", moduleB, "inarray");


  // Create input-buffer.
  fncImageDataPtr inputData(new fncImageData());
  inputData->SetDimensions(100, 100, 100);
  float offset = 0.0f;
  for (int x=0; x <inputData->GetDimensions()[0]; x++)
    {
    for (int y=0; y < inputData->GetDimensions()[1]; y++)
      {
      for (int z=0; z < inputData->GetDimensions()[2]; z++)
        {
        inputData->GetDataPointer(x, y, z)[0] = offset++;
        }
      }
    }

  fncImageDataPtr outputData(new fncImageData());
  outputData->SetDimensions(100, 100, 100);
  memset(outputData->GetData(), 0,
    fncReadableDataTraits<fncImageData>::GetDataSize(NULL, outputData.get()));

  executive->Execute(inputData.get(), outputData.get());
  return 0;
}
