/*=========================================================================

  This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#include "fncExecutive.h"
#include "fncModule.h"
#include "fncAutoGeneratedModule.h"
#include "PassThrough.cl.h"

#include "assert.h"

int main(int, char**)
{
  fncExecutivePtr executive(new fncExecutive());
  fncAutoGeneratedModulePtr moduleA(new fncAutoGeneratedModule());
  assert(moduleA->Initialize(fncHeaderString_PassThrough) != false);

  fncAutoGeneratedModulePtr moduleB(new fncAutoGeneratedModule());
  assert(moduleB->Initialize(fncHeaderString_PassThrough) != false);

  fncAutoGeneratedModulePtr moduleC(new fncAutoGeneratedModule());
  assert(moduleC->Initialize(fncHeaderString_PassThrough) != false);

  executive->Connect(moduleA, "outarray", moduleB, "inarray");
  executive->Connect(moduleA, "outarray", moduleC, "inarray");
  executive->Execute();
  return 0;
}
